# Generated by Django 3.2.9 on 2021-11-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=20)),
                ('information', models.CharField(max_length=250)),
            ],
        ),
    ]
