# Generated by Django 3.2.9 on 2021-11-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0003_auto_20211126_0846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='context',
        ),
    ]
