# Generated by Django 3.2.9 on 2021-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_rename_post_post_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
