# Generated by Django 3.2.9 on 2021-11-27 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0005_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posting_user',
            new_name='user',
        ),
    ]
